### ISSUE TITLE
how to install in linux

### ISSUE THREAD

**Issue by ttx99** [Cyogenus/IPTV-MAC-STALKER-PLAYER#4]
how to install?

**Comment by Cyogenus** [comment]
1. Ensure Python is Installed
First, make sure Python is installed on your Linux system. You can check by running:

bash

python3 --version
If Python is not installed, you can install it using:

bash

sudo apt update
sudo apt install python3 python3-pip
2. Set Up a Virtual Environment (Optional but Recommended)
You can create a virtual environment to isolate your dependencies:

bash

python3 -m venv venv
source venv/bin/activate
3. Install Dependencies
If you haven't created a requirements.txt file yet, use the one generated earlier. Then, install the necessary packages using:

bash

pip install -r requirements.txt
For PyQt5, if you encounter issues, you might need to install system dependencies first:

bash

sudo apt install python3-pyqt5
4. Run Your Script
Once all dependencies are installed, you can run your Python script:

bash

python3 your_script_name.py
Make sure to replace your_script_name.py with the actual filename of your script.

Troubleshooting Dependencies (If needed)
If you encounter issues with PyQt5 on Linux, ensure that you have the necessary development packages:

bash

sudo apt install qt5-default
This should set up the required Qt libraries needed to run PyQt5 applications.

**Comment by ttx99** [comment]
thx

**Comment by Cyogenus** [comment]
> thx

Did you get the player to run ?

**Comment by ttx99** [comment]
super late reply lol 

yes i did
