### ISSUE TITLE
Fix Issue

### ISSUE THREAD

**Issue by Tparag** [Cyogenus/IPTV-MAC-STALKER-PLAYER#9]
### Discussed in https://github.com/Cyogenus/IPTV-MAC-STALKER-PLAYER/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **Tparag** December 21, 2024</sup>
![image](https://github.com/user-attachments/assets/104149e4-14c2-4a0a-9d12-5b366f2158e5)

fix issue in vod ffrt3 error</div>

**Comment by Cyogenus** [comment]
What error are you getting ?

**Comment by Tparag** [comment]
[image: image.png]

This error appears in the movie section

**Comment by Tparag** [comment]
This error appears in the movie section

because - 
 
`if cmd_value.startswith("ffmpeg "):
                        cmd_value = cmd_value[len("ffmpeg ") :]
                    stream_url = cmd_value`
                    
![image](https://github.com/user-attachments/assets/afb0c18c-7bba-4d3b-9616-f980b57b11c2)

**Comment by Tparag** [comment]
And i also added ffmpeg support in this script ☺️

![Screenshot 2024-12-21 210037](https://github.com/user-attachments/assets/1f100195-4170-4553-8a3f-852d784ac1b9)

**Comment by Cyogenus** [comment]
I'll add this fix to the next update. 

Do me a favor and show me what portal url requires this so I can test it out and make sure it works out.

**Comment by Tparag** [comment]
> I'll add this fix to the next update.
> 
> Do me a favor and show me what portal url requires this so I can test it out and make sure it works out.

http://st*rshare.live:8080/c/

**Comment by Cyogenus** [comment]
update code that removes any prefix dynamically from cmd_value, regardless of what it starts with:

This will be in the new update.....     Thanks for the bug report.......

response.raise_for_status()
json_response = response.json()
logging.debug(f"Create link response: {json_response}")
cmd_value = json_response.get("js", {}).get("cmd")

if cmd_value:
    # Remove any prefix (the first word followed by a space)
    cmd_value = ' '.join(cmd_value.split(' ')[1:])
    stream_url = cmd_value
    self.launch_media_player(stream_url)

**Comment by Tparag** [comment]
can you add the ffmpeg support in your next update ?
because if you update this script then i need to update every time for this ffmpeg support

**Comment by Cyogenus** [comment]
This will be in the next update. 

I'm currently stuck getting the tv show playlist navigation to work on stalker portals. I have everything complete but the stupid tv show playlist.
